### ISSUE TITLE
The developer is really really gay!

### ISSUE THREAD

**Issue by UnderscoreKilburn** [UnderscoreKilburn/antibirth-bugs#1]
fucking gay tbh

**Comment by Jvs34** [comment]
ummm still not fixed???

**Comment by Morthcongael** [comment]
I can't believe Kilburn would say something so cruel about the developer of Antibirth. 'Gay' is not only outdated as a derogatory term but it's something that's not nice to say regardless. What did Antibirth's dev do to you, Kilburn?
