### ISSUE TITLE
Blood oath will kill you if you have rotten hearts.

### ISSUE THREAD

**Issue by Morthcongael** [UnderscoreKilburn/antibirth-bugs#14]
I was doing the bloody mary challenge and I had 3 red hearts and a rotten heart with 2 empty heart containers. I went down to the caves 2 and blood oath killed me, presumably by dealing 7 damage to me to take me down to half a red when 7 damage actually killed me from the rotten heart taking 1 damage to die.

Fix - Make blood oath calculate rottens as one hp instead of two.

**Comment by AnonTheMouse** [comment]
I'd like to point out that this is actually a bug with rotten hearts in general. Anything that causes "fake" damage, such as the Charge Machine or the Blood Oath (which from what I can tell simply removes all but a half heart of damage and then calculates how many hits it would have taken to get there) can cause instant death when a rotten heart is involved.

**Comment by UnderscoreKilburn** [comment]
Should be fixed in the next update.
