### ISSUE TITLE
Achievement not crossed out after completing Isaac's awakening.

### ISSUE THREAD

**Issue by clothing5** [UnderscoreKilburn/antibirth-bugs#15]
Just what it says. I did have the same issue as another poster where phase two of the witness didn't happen, but I exited and restarted and finished the fight just fine. It showed the ending cartoon, but then that was it. No unlock notification, and it's still not crossed off.

**Comment by AnonTheMouse** [comment]
To be more correct, the Chest spawns in place of the Trophy, leading to the win not being counted as a challenge victory.

**Comment by UnderscoreKilburn** [comment]
Yup that's a known one, next update will fix it.
