### ISSUE TITLE
New Chapters/Dungeons not showing up. 

### ISSUE THREAD

**Issue by Antichronos** [UnderscoreKilburn/antibirth-bugs#19]
Having an issue where the only part of the mod that is not showing up are the rooms. The monsters, music, and items all show up but regardless of how far I make it the rooms fail to show up even on multiple attempts to restart. I have tried reinstalling the mod entirely and I do not own Afterbirth so that is not an issue either.

**Comment by buttfield** [comment]
Are you referring to the Antibirth-exclusive chapters?
If so, the entrances appear once you've defeated the three new bosses (Baby Plum, Reap Creep, and The Pile) that appear outside of the Antibirth chapters.
