### ISSUE TITLE
Issue: needs to be rewritten in a memory-safe language (Rust)

### ISSUE THREAD

**Issue by portal-chan** [UnderscoreKilburn/antibirth-bugs#2]
Rust is a systems programming language that runs blazingly fast, prevents segfaults, and guarantees thread safety. 

It has:
zero-cost abstractions,
move semantics,
guaranteed memory safety,
threads without data races,
trait-based generics,
pattern matching,
type inference,
minimal runtime,
efficient C bindings.

**Comment by UnderscoreKilburn** [comment]
fucking gay tbh

**Comment by TheSwiftTiger** [comment]
if you wrote it in rust you wouldn't have that main menu memory leak

**Comment by UnderscoreKilburn** [comment]
still gay sys
