### ISSUE TITLE
Red Key to Sheol After Corpse 2

### ISSUE THREAD

**Issue by HEUGH** [UnderscoreKilburn/antibirth-bugs#28]
In the seed 1MNM R64S in normal mode I used the red key to escape the Corpse 2 via an I Am Error room containing a beam of light. However, instead of being taken to the cathedral, the beam of light took me to a broken version of sheol in which satan had been replaced by monstro. Upon defeating monstro I was given no means of progressing, so I used the red key once again to find an angel room with another beam of light that tried to take me to some sort of -1 floor (shown below) which crashed the game upon entering. 
![bug](https://cloud.githubusercontent.com/assets/25572739/22631041/bc5db33a-ebd3-11e6-8246-7b63b6d19638.jpg)

**Comment by UnderscoreKilburn** [comment]
Yes that's a known issue, the Corpse is supposed to be the final level so any level after it will be bugged. Next update will make error rooms in Corpse 2 loop back to itself, similar to error rooms in the Chest or Dark Room.

**Comment by Boingboingsplat** [comment]
Figured I'd add in that this also happens with Black Market trapdoors on the Corpse 2. Just in case your solution doesn't already cover both cases.
