### ISSUE TITLE
Picking up a devil deal worth 2 hearts while having one heart takes away all of your soul hearts,black hearts and immortal hearts

### ISSUE THREAD

**Issue by Animomo** [UnderscoreKilburn/antibirth-bugs#31]
I picked up ceremonial robes worth 2 hearts and it took away my 1 immortal hearts and 3 soul hearts leaving me with only 3 black hearts i got from the robes. It's the devil deal on caves 2
Seed:6KNJ SJY6

**Comment by ZMBanshee** [comment]
It's supposed to happen when you underpay for a devil deal. Not a bug.

**Comment by UnderscoreKilburn** [comment]
Yup, that's intended, no more scamming Satan for you.
