### ISSUE TITLE
Antibirth opens up as Rebirth

### ISSUE THREAD

**Issue by FireheroTAF** [UnderscoreKilburn/antibirth-bugs#34]
So, I tried simply installing Antibirth into my Rebirth folder, but in the beginningit didn't even open up. After a while, I got it to open, but it opens up as normal Rebirth, no matter what I change. I tried installing Antibirth in another folder, on another drive, on desktop.... Nothing worked. I even requested the game files which a friend of mine used to play Antibirth. The files didn't work for me, even though it worked completely fine for him (he had Antibirth installed in the Rebirth folder). After a lot of trying, I'm out of ideas. Can someone help me? I really liked the Antbirth gameplay videos and I want to try it myself....

**Comment by UnderscoreKilburn** [comment]
This might be tied to the way Antibirth injects itself into Rebirth, I'm currently looking into an alternative way of doing it. Which version of Windows are you on? A few other people who had a similar issue reported that running the game in compatibility mode for Windows XP is a good workaround, have you tried that yet?

**Comment by FireheroTAF** [comment]
Thanks, it did it for me too (The Compatibility workaround). Now I can play the game happily ever after... :) (if it helps you with anything, I left the specs, maybe you can find out the issue?...
![capture](https://cloud.githubusercontent.com/assets/25644641/22831148/ea3aadb2-efb1-11e6-93d8-bad05c1301f8.PNG)
)

**Comment by Wyzzcow** [comment]
I know this was marked as closed, but I have the same issue. I've tried all known workarounds (run as admin, compatibility mode) but none work.
I've installed it on my work computer, but sadly at home it just doesn't want to load.
