### ISSUE TITLE
possible game breaking bug

### ISSUE THREAD

**Issue by localwannabe** [UnderscoreKilburn/antibirth-bugs#43]
this is just what I think caused the problem. I was trying to sync my stats into antibirth after reading a thread on reddit on how to fix isaac.ng.exe has stopped responding (i fixed this), and found out how to sync my data to antibirth. after i had attempted to sync it it didnt work and broke the game in this way.
http://steamcommunity.com/sharedfiles/filedetails/?id=861415281  and  https://gyazo.com/5a0e916d49741a0bb5fd1465bed4c015  the gif is rather confusing, i dont quite know why i have afterbirths lost. Anyways, it says im on antibirth but theres some gui's missing, and i cant access the antibirth floors like downpour, mausoleum, etc. when i went back to the thread to see if it happened to anyone else that did this, i didnt see anyone that said it broke their game.

**Comment by buttfield** [comment]
The Lost is intended to have its Afterbirth starting items.
Access to Antibirth floors is unlocked by defeating the three new bosses that appear on standard floors (Baby Plum, Reap Creep, and The Pile).
