### ISSUE TITLE
Schoolbag + Breath of Life = Infinite uses on second held item.

### ISSUE THREAD

**Issue by Thoronir42** [UnderscoreKilburn/antibirth-bugs#45]
This game break is just... breathtaking. 😛 

edit: Wowie. I accidentally did my research After submitting this issue and this behaviour is apparently listed as a feature.
Though I honestly think that this really just messes up all the balance TBOI might or might not have had in first place.

**Comment by buttfield** [comment]
In fairness, it does require an Angel Room-exclusive item, a Shop-exclusive item, and a second active item capable of being abused.

**Comment by Thoronir42** [comment]
Well that does sound like a fair amount of work. Alrighty, thanks for having me actually realize what I've achieved. It felt crazy to find a new way to break the game.
