### ISSUE TITLE
Unsolvable Ending in sheol on "isaacs awakening" preceded by unusual / senseless stuff

### ISSUE THREAD

**Issue by MartinDobisch** [UnderscoreKilburn/antibirth-bugs#68]
I played the challenge "isaacs awakening" and managed to kill me some angels and get the mega satan key.

Right before the witness i got into an angelroom via red chest. 
I took the beam of light and got to sheol (i had the negative, since i didn't unlock the polaroid on my antibirth savegame yet). 

There was no Satan in the Bossroom, but Monstro was.
Of course Monstro didn't spawn a golden chest on depature so i got stuck in Sheol.

Edit:  Seed 63SE TQBB

PS: THANKS for all your work. Antibirth got me back to isaac and i am running for the quadruple digits of playtime now :)

**Comment by Boingboingsplat** [comment]
Similar to #28 

Looks like anything that can take you past Corpse II results in this.

**Comment by MartinDobisch** [comment]
Agreed, i managed to reproduce it twice today.
Once via Beam of light and once via error room.

Since this issue was allready adressed, i am going to close here.

sidenote:
I totally get, that corpse II is the final level, but i'd really love to kill the witness and megasatan in the same run.
