### ISSUE TITLE
I fought the witness way too early

### ISSUE THREAD

**Issue by sdsas** [UnderscoreKilburn/antibirth-bugs#88]
Here's my seed ZZLB AY22. I was on an Xl floor when after I killed the second boss. I saw a third boss door going up. I entered it and I started fighting the witness. Here's a screenshot 
![untitled](https://cloud.githubusercontent.com/assets/26839602/24579677/ba565c8a-16ae-11e7-9f8e-ed5b59f8e106.png)

**Comment by sdsas** [comment]
I tried replicating it but I couldn't. I got a guardian angel from the angel room then when I left I saw the third boss room the first time.

**Comment by LinkTheLinker** [comment]
This issue is similar to issue #64.

**Comment by sdsas** [comment]
Ah, you're right. Sorry for wasting your time.
